services:

  database:
    image: churchmutual/database
    build:
      dockerfile: ./docker-compose/database/Dockerfile
      context: ./
    environment:
      - MSSQL_SA_PASSWORD=Liferay123!
      - ACCEPT_EULA=Y
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-USA", "-PLiferay123!", "-Q", "select 1"]
    ports:
      - "1433:1433"

  liferay:
    image: liferay/dxp:7.2.10-dxp-8
    environment:
      - LIFERAY_JVM_OPTS=-Xms4g -Xmx4g -Djdk.util.zip.disableZip64ExtraFieldValidation=true
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:sqlserver://database;databaseName=Liferay;encrypt=true;trustServerCertificate=true
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=sa
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=Liferay123!
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY=20
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES=5
      - LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE=domain
      - JAVA_VERSION=zulu11
    ports:
      - "8080:8080"
      - "11311:11311"
      - "8000:8000"
    volumes:
      - ./docker-compose/liferay-files:/mnt/liferay/files
      - ./docker-compose/liferay-scripts:/mnt/liferay/scripts
      - ./bundles/deploy:/mnt/liferay/deploy
      - ./bundles/osgi/modules:/opt/liferay/osgi/modules
      - ./bundles/osgi/configs:/opt/liferay/osgi/configs
      - ./bundles/osgi/war:/opt/liferay/osgi/war
      - ./bundles/logs:/opt/liferay/logs
      - ./bundles/data/document_library:/opt/liferay/data/document_library
    depends_on:
      database:
        condition: service_healthy
      search:
        condition: service_started

  search:
    image: baseline/elasticsearch
    build: ./docker-compose/elasticsearch/
    environment:
      - cluster.name=LiferayElasticsearchCluster
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "discovery.type=single-node"
      - "node.name=es-node1"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

networks:
  mynetwork:
    driver: bridge

volumes:
  elastic-data: